title: 'Bertrand Caron - Academic Curriculum Vitae'
first_name: Bertrand
last_name: Caron
url: 'bcaron.me'
img_name: 'B_Caron_1000px.jpg'
mobile: '+61 4 66 575 476'
profile: 'Graduate student holding a M.Sc in Theoretical Bio-Chemistry undergoing a PhD at the University of Queensland, Australia'
occupation: 'PhD Student'
age: '24'
social:
  github: bertrand-caron
  linked_in: bertrandcaron
  stack_overflow:
    user_id: 1680996
    username: bertrand-caron
  email: 'bertrand@bcaron.me'
