name: Build and test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make pip
    # - name: Analysing the code with pylint
    #   run: |
    #     make pylint
    - name: Run code coverage
      run: |
        make coverage
    # - name: Run type checks
    #   run: |
    #     make mypy
